# Copyright (c) 2018 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# NOTE: To be used with k8s >= 1.8.1, < 1.9.0 (or with k8s >= 1.9.0 if webhook is not used).

apiVersion: v1
kind: Pod
metadata:
  labels:
    app: cmk-isolate-pod
  name: cmk-isolate-pod
  namespace: cmk-namespace
spec:
  serviceAccountName: cmk-serviceaccount
  tolerations:
  - operator: "Exists"
  restartPolicy: Never
  containers:
  - name: cmk-isolate-exclusive-non-isolcpus
    image: cmk:v1.5.1
    command:
    - "/bin/bash"
    - "-c"
    args:
    - "/opt/bin/cmk isolate --conf-dir=/etc/cmk --pool=exclusive-non-isolcpus echo -- Hello World Exclusive-Non-Isolcpus!!!"
    resources:
      requests:
        cmk.intel.com/exclusive-non-isolcpus-cores: '1'
      limits:
        cmk.intel.com/exclusive-non-isolcpus-cores: '1'
    env:
    - name: CMK_PROC_FS
      value: "/host/proc"
    volumeMounts:
    - mountPath: "/host/proc"
      name: cmk-host-proc
      readOnly: true
    - mountPath: "/opt/bin"
      name: cmk-install-dir
    - mountPath: "/etc/cmk"
      name: cmk-conf-dir
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      capabilities:
        drop:
          - all
  volumes:
  - hostPath:
      # Change this to modify the CMK installation dir in the host file system.
      path: "/opt/bin"
    name: cmk-install-dir
  - hostPath:
      path: "/proc"
    name: cmk-host-proc
  - hostPath:
      # Change this to modify the CMK config dir in the host file system.
      path: "/etc/cmk"
    name: cmk-conf-dir
