# Copyright (c) 2017 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: cmk-init-pod
  name: cmk-init-pod
spec:
  serviceAccountName: cmk-serviceaccount
  containers:
  - args:
    - "/cmk/cmk.py init --conf-dir=/etc/cmk --num-dp-cores=$NUM_DP_CORES --num-cp-cores=$NUM_CP_CORES"
    command:
    - "/bin/bash"
    - "-c"
    env:
    - name: CMK_PROC_FS
      value: '/proc'
    - name: NUM_DP_CORES
      # Change this to modify the value passed to `--num-dp-cores` flag.
      value: '4'
    - name: NUM_CP_CORES
      # Change this to modify the value passed to `--num-cp-cores` flag.
      value: '1'
    image: cmk:v1.2.2
    name: cmk-init-pod
    volumeMounts:
    - mountPath: "/etc/cmk"
      name: cmk-conf-dir
  restartPolicy: Never
  volumes:
  - hostPath:
      # Change this to modify the CMK config dir in the host file system.
      path: "/etc/cmk"
    name: cmk-conf-dir
