# Copyright (c) 2017 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: kcm-cluster-init-pod
  annotations:
    "scheduler.alpha.kubernetes.io/tolerations": '[{"key":"kcm", "value":"true"}]'
  name: kcm-cluster-init-pod
spec:
  containers:
  - args:
      # Change this value to pass different options to cluster-init.
      - "/kcm/kcm.py cluster-init --host-list=node1,node2,node3"
    command:
    - "/bin/bash"
    - "-c"
    image: kcm:v0.5.0
    name: kcm-cluster-init-pod
  restartPolicy: Never
