apiVersion: v1
kind: Service
metadata:
  name: cmk-webhook-service
  labels:
    app: cmk-webhook-app
  #namespace: user-supplied-namespace
spec:
  ports:
  - port: 443
    targetPort: 443
  selector:
    app: cmk-webhook-app
